site_name: "SDX API Standards"
site_description: "Secure Data Exchange (SDX) API standards documentation"
docs_dir: "docs"
repo_url: "https://github.com/bcgov/csit-api-governance-spectral-style-guide"
edit_uri: edit/main/techdocs/sdx-api-standards/docs
nav:
    - index.md
plugins:
    - techdocs-core
markdown_extensions:
    - md_in_html
    - admonition
