name: Build TechDocs with DevHub TechDocs Publish Action

permissions:
    contents: read

on:
    workflow_dispatch:
    push:
        branches: [ main ]
        paths:
            - "catalog-info.yaml"
            - "**/catalog-info.yaml"
            - "**/mkdocs.yml"
            - "**/docs/**"
    pull_request:
        branches: [ main ]
        paths:
            - "catalog-info.yaml"
            - "**/catalog-info.yaml"
            - "**/mkdocs.yml"
            - "**/docs/**"

jobs:
    test_techdocs_build_job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                techdocs_directory:
                    - techdocs/api-style-guides
                    - techdocs/sdx-api-standards

        name: Build ${{ matrix.techdocs_directory }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v5
                with:
                    fetch-depth: '0'
            -   name: Stage TechDocs component
                env:
                    TECHDOCS_DIRECTORY: ${{ matrix.techdocs_directory }}
                run: |
                    cp "${TECHDOCS_DIRECTORY}/catalog-info.yaml" catalog-info.techdocs.yaml
                    cp "${TECHDOCS_DIRECTORY}/mkdocs.yml" mkdocs.yml
                    cp -R "${TECHDOCS_DIRECTORY}/docs" docs
                    find techdocs -type f \( -name catalog-info.yaml -o -name catalog-info.yml \) -delete
                    mv catalog-info.techdocs.yaml catalog-info.yaml
            -   name: Build TechDocs
                uses: bcgov/devhub-techdocs-publish@stable
                id: build_and_publish
                with:
                    publish: 'true'
                    production:  ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
                    bucket_name: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
                    s3_access_key_id: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
                    s3_secret_access_key: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
                    s3_region: ${{ secrets.TECHDOCS_AWS_REGION }}
                    s3_endpoint: ${{ secrets.TECHDOCS_AWS_ENDPOINT }}
